### ISSUE TITLE
gem error

### ISSUE THREAD

**Issue by yossiedri** [bmalets/d3-charts#4]
Hi 
im geting this error trying to use this gem, please note my rails 4 app doesn't use asset pipeline so i included the 3d.min.js in the header.

ActionView::Template::Error (No such file or directory - app/assets/javascripts/d3-charts):
  3: <%= horizontal_bar_chart( [1,2,3,4,5] ) %>

please advice...
thanks 
yossi

**Comment by bmalets** [comment]
Hi Yossi!

Currently this gem supports Rails 3 only. 
But on this weekends I will create new branch for the newest versions of Rails, Ruby and D3.js.

So, on the next week a new version of "d3-charts" gem will be released, specially for your needs and your environment. And I will write good detailed documentation for this gem.

Thanks for using "d3-charts"!

Kindly Regards,
Bohdan

**Comment by yossiedri** [comment]
thank you for the quick response
I’m looking forward for the next release
thanks
yossi
