### ISSUE TITLE
d3.charts apparently creating assets ?

### ISSUE THREAD

**Issue by thobruk** [bmalets/d3-charts#5]
This gem works in the most bizarre way. It takes my calls and converts them into assets. The problem is that my data changes and the script generated to display the chart does not. Why on earth does this write scripts into my assets tree ? It's extremely unusual and makes me not want to use it.

**Comment by bohdan-malets** [comment]
Hi @thobruk,

   Sorry, I'm too busy now and don't have many time for this gem :(
   And sorry for pushing chart's css into your assets. I am planning to fix it in next version.

   Please, give me an advise how make it better. And I will implement it in new rails_4 branch.
   Also, I will be very happy if you become a contributor of this gem, fork it and make pull request.

Thanks kindly,
Bohdan
